### ISSUE TITLE
截止2024年3月5日这个项目还可以正常运行吗？

### ISSUE THREAD

**Issue by atorber** [AvengersWeChat/PadChat-SDK#25]
如题

**Comment by limcod** [comment]
我也想知道

**Comment by brisk21** [comment]
封号了
![IMG (33)](https://github.com/AvengersWeChat/PadChat-SDK/assets/17331991/9f54e963-5756-471a-9914-c4a04b4e161e)

**Comment by moshuchao** [comment]
啥情况
